debug: false
security:
  jwt:
    token:
      secret-key: admin
      expire-length: 3600000
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gerenciador_db?useTimeZone=false&serverTimezone=America/Sao_Paulo
      username: root
      password: bremissor_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false